export const USER_ROUTES = {
  ROOT: "/",
  HOME: "/home",
  REGISTER: "/users/register",
  LOGIN: "/users/login",
  VERIFY_OTP: "/users/verify-otp",
  FORGOT_PASSWORD: "/users/forgotpassword",
  RESET_PASSWORD: "/users/resetpassword",
  FORGOT_OTP: "/users/reset-verify-otp",
  GOOGLE_VERIFY: "/users/google-verify",
  PROFILE: "/users/profile",
  COURSES: "/users/courses",
  COURSE_DETAIL: (courseId: string = ":courseId") =>
    `/users/courses/${courseId}`,
  COURSE_VIEW: (courseId: string = ":courseId") =>
    `/users/course-view/${courseId}`,
  NOTIFICATIONS: `/users/notifications`,
  LEARNING_PATHS: "/users/learning-paths",
  PURCHASE_HISTORY: `/users/purchasehistory`,
  WALLET: `/users/wallet`,
  CHAT_PAGE: `/users/chat`,
  CHAT_WINDOW: (chatId: string = ".chatId") => `/users/chat/${chatId}`,
  VIDEO_CALL: (chatId: string = ":chatId") => `/users/video/${chatId}`,
  PURCHASED_COURSES: `/users/purchase-courses`,
  CHANGE_PASSWORD: `/users/change-password`,
  CERTIFICATES: `/users/certificates`,
} as const;

export const INSTRUCTOR_ROUTES = {
  REGISTER: "/instructors/register",
  LOGIN: "/instructors/login",
  VERIFY_OTP: "/instructors/verify-otp",
  FORGOT_OTP: "/instructors/reset-verify-otp",
  FORGOT_PASSWORD: "/instrcutors/forgotpassword",
  RESET_PASSWORD: "/instructors/resetpassword",
  BASE: "/instructors",
  DASHBOARD: "/instructors/dashboard",
  CREATE_COURSE: "/instructors/create-course",
  PROFILE: "/instructors/profile",
  COURSES: "/instructors/courses",
  CHAT_PAGE:`/instructors/chat`,
  VIDEO_CALL:`/instructors/video`,
  EDIT_COURSE:(courseId:string = ":courseId")=>`/instructors/courses/${courseId}`,
  REVIEWS:`/instructors/reviews`,
  EARNINGS:`/instructors/earnings`,
  ENROLLMENTS:`/instructors/enrollments`,
  NOTIFICATIONS:`/instructors/notifications`,
  CREATEQUIZ:(courseId:string = ":courseId")=>`/instructors/courses/create-quiz/${courseId}`,
  MANAGE_QUIZ:(quizId:string = ":quizId")=>`/instructors/quiz/${quizId}`,
  QUIZ:`/instructors/quiz`,
  COURSE_PROGRESS:(courseId:string = ":courseId")=>`/instructors/courses/${courseId}/progress`
} as const;

export const ADMIN_ROUTES = {
  LOGIN: "/admin/login",
  COURSES: "/admin/courses",
  DASHBOARD: "/admin/dashboard",
  BASE: "/admin",
  USERS: "/admin/users",
  TUTORS: "/admin/tutors",
  TUTOR_REQUESTS: "/admin/tutor-requests",
  CATEGORY: "/admin/category",
  TUTOR_VIEW: (tutorId: string = ":tutorId") => `/admin/tutor-view/${tutorId}`,
  REVIEWS: `/admin/reviews`,
  COMPLAINTS: `/admin/complaints`,
  EARNINGS: `/admin/earnings`,
  COURSE_VIEW: (courseId: string = ":courseId") => `/admin/courses/${courseId}`,
  NOTIFICATIONS: `/admin/notifications`,
  USER_ACTIVITY_REPORT: `/admin/reports/user-activity`,
  COURSE_PERFORMANCE_REPORT: `/admin/reports/course-performance`,
} as const;
